### ISSUE TITLE
Todo: Support Adding Twig Extensions

### ISSUE THREAD

**Issue by sghoweri** [basaltinc/twig-renderer#6]

**Comment by EvanLovely** [comment]
Done. Doable like so:

https://github.com/basaltinc/twig-renderer/blob/master/__tests__/twig-extensions/twig-extensions.js#L9-L12

You can pass a series of php files and there functions to call that get passed what you see here:

https://github.com/basaltinc/twig-renderer/blob/master/__tests__/twig-extensions/alter-twig.php

and since you get passed the whole Twig Env, you can do whatever that can do; one of them being adding Twig Extensions.
